name = "ExoMol"
uuid = "ad33b8ab-ae41-41db-81f7-3b0c63c48de0"
authors = ["Jan Kuhfeld <jan.kuhfeld@rub.de> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
