name = "ExoMol"
uuid = "ad33b8ab-ae41-41db-81f7-3b0c63c48de0"
authors = ["Jan Kuhfeld <jan.kuhfeld@rub.de> and contributors"]
version = "1.0.0-DEV"

[deps]
FixedWidthTables = "ef6c9296-b25d-482c-a0a7-898918678e13"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"

[compat]
JSON = "0.21.4"
SafeTestsets = "0.1.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
