name = "ExoMol"
uuid = "ad33b8ab-ae41-41db-81f7-3b0c63c48de0"
authors = ["Jan Kuhfeld <jan.kuhfeld@rub.de> and contributors"]
version = "1.0.0-DEV"

[deps]
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"

[compat]
CSV = "0.10.15"
DataFrames = "1.7.0"
julia = "1.6.7"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
